### ISSUE TITLE
installing jsx and react-meteor-data

### ISSUE THREAD

**Issue by zeroasterisk** [Meteor-Alt/react#1]
This package is installing extra Meteor packages which it doesn't need to.

```
$ meteor add alt:react-accounts-unstyled

alt:react                    added, version 1.0.2
alt:react-accounts-unstyled  added, version 1.2.1
jsx                          added, version 0.2.4
react-meteor-data            added, version 0.1.9
```

Possibly related, after installing it's causing my new app to crash, has all the React npm modules installed:

```
=> Modified -- restarting.
W20160410-23:31:50.109(-4)? (STDERR) WARNING: npm peer requirements not installed:
W20160410-23:31:50.109(-4)? (STDERR)  - react@0.14.8 installed, react@15.x needed
W20160410-23:31:50.109(-4)? (STDERR)  - react-addons-pure-render-mixin@15.x not installed.
W20160410-23:31:50.109(-4)? (STDERR)
W20160410-23:31:50.109(-4)? (STDERR) Read more about installing npm peer dependencies:
W20160410-23:31:50.109(-4)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20160410-23:31:50.110(-4)? (STDERR)
W20160410-23:31:50.198(-4)? (STDERR)
W20160410-23:31:50.199(-4)? (STDERR) /Users/alan/.meteor/packages/meteor-tool/.1.3.1.6u43i0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160410-23:31:50.199(-4)? (STDERR)            				throw(ex);
W20160410-23:31:50.199(-4)? (STDERR)            				      ^
W20160410-23:31:50.205(-4)? (STDERR) Error: Can't find npm module 'react-addons-pure-render-mixin'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20160410-23:31:50.205(-4)? (STDERR)     at Object.Npm.require (/Users/alan/Code/eltoro/portal_v2/webapp/.meteor/local/build/programs/server/boot.js:195:17)
W20160410-23:31:50.205(-4)? (STDERR)     at options.fallback (packages/modules-runtime.js:413:18)
W20160410-23:31:50.205(-4)? (STDERR)     at require (packages/modules-runtime.js:98:16)
W20160410-23:31:50.205(-4)? (STDERR)     at meteorInstall.node_modules.meteor.react-meteor-data.createContainer.jsx (packages/react-meteor-data/createContainer.jsx:6:1)
W20160410-23:31:50.205(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:158:9)
W20160410-23:31:50.206(-4)? (STDERR)     at require (packages/modules-runtime.js:92:16)
```

**Comment by emmostrom** [comment]
MDG still says best practice is to use react-meteor-data for the for the reactive mixin - but it looks like their latest version is expecting you to use React 15 instead of 14.  A temporary fix is to edit your .meteor/versions file and change react-meteor-data to 0.1.4.

I will figure out a fix to put out soon that doesn't use react-meteor-data.

**Comment by emmostrom** [comment]
I actually can't reproduce this.  If I take a new 1.3.1 app with npm react 14 installed and then add in alt:react-accounts-unstyled I get meteor-react-data:0.1.9 which is ok and doesn't cause the error you are seeing.  Maybe there is another package you have installed that is using meteor react packages?

I will go ahead and try to remove the dependency on react-meteor-data but I don't think this is causing the error you are seeing.

**Comment by emmostrom** [comment]
Removed react-meteor-data dependency.
